package com.example.bhumisewa.utils

import com.example.bhumisewa.model.House

object MockData {

    val houses = listOf(
        House(
            houseId = "house_001",
            title = "Modern 2BHK Apartment",
            description = "A beautifully designed 2-bedroom apartment in the heart of Kathmandu. Fully furnished with modern appliances, 24/7 water supply, backup power, and stunning city views. Perfect for professionals or small families.",
            address = "Lazimpat, Ward 2",
            city = "Kathmandu",
            district = "Kathmandu",
            type = "Apartment",
            bedrooms = 2,
            bathrooms = 2,
            area = "950 sq ft",
            floor = "4th Floor",
            furnished = "Furnished",
            price = "Rs. 35,000/mo",
            priceValue = 35000L,
            depositAmount = "Rs. 70,000",
            availableFrom = "Immediately",
            imageUrl = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
            amenities = listOf("WiFi", "Parking", "Security", "Water 24/7", "Power Backup", "Lift"),
            rating = 4.7f,
            reviewCount = 12,
            isFeatured = true,
            isAvailable = true,
            ownerName = "Rajesh Sharma",
            ownerPhone = "+977-9801234567",
            ownerEmail = "rajesh@email.com"
        ),
        House(
            houseId = "house_002",
            title = "Spacious 3BHK Family House",
            description = "A large independent house ideal for families. Features a garden, private parking for 2 cars, solar water heater, and a rooftop terrace with Himalayan views. Quiet residential area.",
            address = "Budhanilkantha, Ward 5",
            city = "Kathmandu",
            district = "Kathmandu",
            type = "House",
            bedrooms = 3,
            bathrooms = 3,
            area = "1800 sq ft",
            floor = "2 Floors",
            furnished = "Semi-Furnished",
            price = "Rs. 55,000/mo",
            priceValue = 55000L,
            depositAmount = "Rs. 1,10,000",
            availableFrom = "15 Jan 2026",
            imageUrl = "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
            amenities = listOf("Garden", "Parking", "Security", "Solar Water", "Rooftop", "WiFi"),
            rating = 4.9f,
            reviewCount = 8,
            isFeatured = true,
            isAvailable = true,
            ownerName = "Sunita Thapa",
            ownerPhone = "+977-9807654321",
            ownerEmail = "sunita@email.com"
        ),
        House(
            houseId = "house_003",
            title = "Cozy Studio Apartment",
            description = "A smart studio apartment perfect for students or working professionals. Fully furnished with a kitchenette, modern bathroom, and high-speed WiFi. Walking distance to IT Park.",
            address = "Kumaripati, Lalitpur",
            city = "Lalitpur",
            district = "Lalitpur",
            type = "Studio",
            bedrooms = 1,
            bathrooms = 1,
            area = "420 sq ft",
            floor = "2nd Floor",
            furnished = "Furnished",
            price = "Rs. 18,000/mo",
            priceValue = 18000L,
            depositAmount = "Rs. 36,000",
            availableFrom = "Immediately",
            imageUrl = "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
            amenities = listOf("WiFi", "Water 24/7", "Security", "Power Backup"),
            rating = 4.3f,
            reviewCount = 19,
            isFeatured = false,
            isAvailable = true,
            ownerName = "Bikash Rai",
            ownerPhone = "+977-9841122334",
            ownerEmail = "bikash@email.com"
        ),
        House(
            houseId = "house_004",
            title = "Luxury 4BHK Villa",
            description = "An exclusive villa in Pokhara with stunning lake and mountain views. Features a private swimming pool, landscaped garden, home theatre, and smart home system. Ideal for high-end living.",
            address = "Lakeside, Baidam",
            city = "Pokhara",
            district = "Kaski",
            type = "Villa",
            bedrooms = 4,
            bathrooms = 4,
            area = "3200 sq ft",
            floor = "3 Floors",
            furnished = "Furnished",
            price = "Rs. 1,20,000/mo",
            priceValue = 120000L,
            depositAmount = "Rs. 2,40,000",
            availableFrom = "1 Feb 2026",
            imageUrl = "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800",
            amenities = listOf("Pool", "Garden", "Parking", "Security", "WiFi", "CCTV", "Home Theatre", "Smart Home"),
            rating = 5.0f,
            reviewCount = 5,
            isFeatured = true,
            isAvailable = true,
            ownerName = "Arun Gurung",
            ownerPhone = "+977-9855667788",
            ownerEmail = "arun@email.com"
        ),
        House(
            houseId = "house_005",
            title = "1BHK Near Teaching Hospital",
            description = "Affordable 1-bedroom apartment close to Maharajgunj Teaching Hospital and embassies. Ideal for medical students, interns, or diplomats. Regular water supply and good connectivity.",
            address = "Maharajgunj, Ward 4",
            city = "Kathmandu",
            district = "Kathmandu",
            type = "Apartment",
            bedrooms = 1,
            bathrooms = 1,
            area = "600 sq ft",
            floor = "1st Floor",
            furnished = "Semi-Furnished",
            price = "Rs. 22,000/mo",
            priceValue = 22000L,
            depositAmount = "Rs. 44,000",
            availableFrom = "Immediately",
            imageUrl = "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
            amenities = listOf("WiFi", "Water 24/7", "Parking", "Security"),
            rating = 4.1f,
            reviewCount = 23,
            isFeatured = false,
            isAvailable = true,
            ownerName = "Pawan Shrestha",
            ownerPhone = "+977-9862233445",
            ownerEmail = "pawan@email.com"
        ),
        House(
            houseId = "house_006",
            title = "Premium 2BHK in Patan",
            description = "A heritage-inspired modern apartment in the cultural hub of Patan. Exposed brick interiors, wooden flooring, and a private balcony overlooking the courtyard. Minutes from Patan Durbar Square.",
            address = "Mangal Bazar, Patan",
            city = "Lalitpur",
            district = "Lalitpur",
            type = "Apartment",
            bedrooms = 2,
            bathrooms = 2,
            area = "1050 sq ft",
            floor = "3rd Floor",
            furnished = "Furnished",
            price = "Rs. 42,000/mo",
            priceValue = 42000L,
            depositAmount = "Rs. 84,000",
            availableFrom = "Immediately",
            imageUrl = "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
            amenities = listOf("WiFi", "Balcony", "Security", "Water 24/7", "Power Backup", "Parking"),
            rating = 4.8f,
            reviewCount = 14,
            isFeatured = true,
            isAvailable = true,
            ownerName = "Kamala Joshi",
            ownerPhone = "+977-9871234560",
            ownerEmail = "kamala@email.com"
        )
    )

    val apartments get() = houses.filter { it.type == "Apartment" }
    val villas     get() = houses.filter { it.type == "Villa" }
    val studios    get() = houses.filter { it.type == "Studio" }
    val featured   get() = houses.filter { it.isFeatured }
}